apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naratel-dashboard-ingress
  namespace: default
  annotations:
    # Standard Nginx Ingress annotations
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Set to "true" if using TLS
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # Replace with your actual domain
    - host: dashboard.naratel.local 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: naratel-dashboard-svc
                port:
                  number: 80
  # Uncomment for TLS
  # tls:
  #   - hosts:
  #       - dashboard.naratel.local
  #     secretName: naratel-dashboard-tls
