apiVersion: v1
kind: Service
metadata:
  name: naratel-dashboard-svc
  namespace: default
spec:
  selector:
    app: naratel-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
